// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1wCYpTTwuLGylAK18Wb08zOdt1njzeKc',
    appId: '1:937442611205:web:5aa578f714ba31ec994c6c',
    messagingSenderId: '937442611205',
    projectId: 'ecosight-35d2b',
    authDomain: 'ecosight-35d2b.firebaseapp.com',
    storageBucket: 'ecosight-35d2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnVreww9JhQ1_qp_SSZbuqwntx1GWgVVg',
    appId: '1:937442611205:android:38f938308d49d1d6994c6c',
    messagingSenderId: '937442611205',
    projectId: 'ecosight-35d2b',
    storageBucket: 'ecosight-35d2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVUeJgPJNFoFGGZTrWT91Anautn5gPcdc',
    appId: '1:937442611205:ios:738360c15b7aea05994c6c',
    messagingSenderId: '937442611205',
    projectId: 'ecosight-35d2b',
    storageBucket: 'ecosight-35d2b.firebasestorage.app',
    iosBundleId: 'com.ecosight.ecosightClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVUeJgPJNFoFGGZTrWT91Anautn5gPcdc',
    appId: '1:937442611205:ios:738360c15b7aea05994c6c',
    messagingSenderId: '937442611205',
    projectId: 'ecosight-35d2b',
    storageBucket: 'ecosight-35d2b.firebasestorage.app',
    iosBundleId: 'com.ecosight.ecosightClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1wCYpTTwuLGylAK18Wb08zOdt1njzeKc',
    appId: '1:937442611205:web:3289c5b33e196bad994c6c',
    messagingSenderId: '937442611205',
    projectId: 'ecosight-35d2b',
    authDomain: 'ecosight-35d2b.firebaseapp.com',
    storageBucket: 'ecosight-35d2b.firebasestorage.app',
  );
}
